input type:keyboard {
    xkb_layout us,ir
    xkb_options grp:win_space_toggle 
}

input type:touchpad {
    tap enabled
    click_method clickfinger
    dwt enabled
    natural_scroll disabled
    middle_emulation enabled
}
