include colors

# Window borders
default_border normal

# Gaps
gaps inner 6
gaps outer 6

smart_gaps off
smart_borders off

set $focused.color1 #551b6c
set $focused.color11 #7a259b
set $focused.color2 #f2e4f8

set $unfocused.color1 #323032
set $unfocused.color2 #a9a7a7

set $urgent.color1 #a82910
set $urgent.color2 #f8e2e2

# Window decorations:    border,             background,            text,               indicator,          child-border
client.focused           $focused.color1     $focused.color1        $focused.color2     $focused.color11    $focused.color1
client.focused_inactive  $unfocused.color1   $unfocused.color1      $unfocused.color2   $unfocused.color1   $unfocused.color1
client.unfocused         $unfocused.color1   $unfocused.color1      $unfocused.color2   $unfocused.color1   $unfocused.color1
client.urgent            $urgent.color1      $urgent.color2         $urgent.color1      $urgent.color2      $urgent.color1
client.placeholder       $focused.color1     $focused.color1        $focused.color2     $focused.color11    $focused.color1
client.background        $focused.color1


# disable focus follows mouse
focus_follows_mouse no

# Title format for windows
for_window [shell="xdg_shell"] title_format "%title (%app_id)"
for_window [shell="x_wayland"] title_format "%class - %title"

set $opacity 1

for_window [class=".*"] opacity $opacity
for_window [app_id=".*"] opacity $opacity

#----------------#
# set gtk+ theme #
#----------------#
seat * xcursor_theme breeze_cursors 26
set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set $gnome-schema gtk-theme 'Yaru-olive-dark'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
    gsettings set $gnome-schema icon-theme 'Yaru-olive-dark'
    gsettings set $gnome-schema cursor-theme 'breeze_cursors'
    gsettings set $gnome-schema cursor-size 26
}


