for_window [app_id="Alacritty"] move container to workspace number 1; workspace number 1
for_window [app_id="brave-browser"] move container to workspace number 2; workspace number 2
for_window [app_id="code"] move container to workspace number 3; workspace number 3