#!/usr/bin/env bash

echo "Adding Brave repo"

if grep -Rq '^\[brave-browser\]' /etc/yum.repos.d/*.repo 2>/dev/null; then
    echo "Brave repository already exists."
else
    echo "Adding Brave repository..."
    sudo dnf config-manager addrepo \
        --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
fi

echo "Done."
