#!/usr/bin/env bash

set -euo pipefail

# =========================================================
# Install SDKMAN!
# =========================================================
if [ -d "${HOME}/.sdkman" ]; then
    echo "✓ SDKMAN! is already installed. Skipping."
else
    echo "Installing SDKMAN!..."
    curl -s "https://get.sdkman.io?rcupdate=false" | zsh
fi

