#!/usr/bin/env bash

set -euo pipefail

echo "Updating system..."

sudo dnf update --refresh -y

sudo dnf group install -y development-tools 

echo "Setup extra repos"
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf copr enable dejan/lazygit -y
sudo dnf copr enable atim/starship -y
source ./_brave
source ./_code

echo "Installing packages..."

packages=(
    # System Tools & Shell Enhancements
#    base-devel     uwsm libnewt  
    # dunst pipewire wireplumber udisks2 udiskie
    zsh eza bat fd fzf zoxide ripgrep stow  fontconfig tmux remmina 
    ntfs-3g btop bash-completion zip unzip unrar file-roller wl-clipboard cliphist
    less zsh zsh-autosuggestions zsh-syntax-highlighting
    alacritty starship persepolis kanshi dnf-plugins-core
    
#    # ghostty ghostty-nautilus
#
#    # GNOME Desktop
     xdg-desktop-portal-gtk gvfs gtk3 gtk4 glib2
     gnome-keyring nautilus
#
#    # Themes
     yaru-icon-theme yaru-gtk4-theme yaru-gtk3-theme breeze-cursor-theme
     rsms-inter-fonts
     # nwg-look

     # Graphics
     akmod-nvidia-580xx xorg-x11-drv-nvidia-580xx xorg-x11-drv-nvidia-580xx-cuda
     mesa-demos qt6ct qt5ct kvantum
     
     # Gaming 
     steam mangohud gamemode vulkan-tools mesa-vulkan-drivers

     # Networking
     NetworkManager NetworkManager-openconnect openconnect tor obfs4
     openfortivpn

    # Multimedia
     mpv celluloid brave-browser waybar loupe ffmpeg discord
    # photoflare

     # Docker
     docker-cli containerd docker-compose docker-compose-switch

     # Development
     code git gh lazygit neovim nodejs npm 
     clang lld llvm libX11-devel libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel 
     mesa-libGL-devel mesa-libEGL-devel wayland-devel libxkbcommon-devel
     mingw64-gcc mingw64-binutils
)

sudo dnf install -y "${packages[@]}"

echo "Running post-install scripts..."

source ./_rust
source ./_sdkman
# source ./_nvm # TODO not ready yet
source ./_ollama
source ./_zsh
source ./_mime-defaults
source ./_docker
source ./_nvidia
# source ./nopass-openconnect

echo "Done."
